### ISSUE TITLE
Will the refund work after a few matches?

### ISSUE THREAD

**Issue by Tobi1446** [KebsCS/KBotExt#137]
Lets say I used aram boost in first match and lost my rp, then played 4-5 games with no boost, after stopping playing and waiting 1 hour will the refund work?

**Comment by bit-paper** [comment]
yes, and actually you could use the boost multiple times. it won't eat rp again until refund. just remember to press refund after atleast 1 hour. (my friend forget about it and pressed refund on the next day and it worked)

**Comment by tragedyxxms** [comment]
**Listen clearly and distinctly.**
Boost exploit works so that you boost (buy a character to RP that you cannot PLAY! Let me give an example of myself: 
I use ARAM Boost and it buys me a character **Annie**, which I can't play because it won't refund my RP).

After playing, you can use the boost for the next 24hrs, but be sure to click Refund button before the 24 hours are up, so it's best to wait more than 1 hour after the last game. If you use the Refund before 1 hour, for example, 30 minutes after the match, RP will be consumed and you will never see them back.

**Comment by Tobi1446** [comment]
I see, I thought I had to wait 1 hour after each game, I love you guys thanks.
