### ISSUE TITLE
Free Tristana + Riot Girl Skin Not Working Anymore

### ISSUE THREAD

**Issue by kunaiul** [KebsCS/KBotExt#19]
![Untitled](https://user-images.githubusercontent.com/91280422/134555855-a0646258-b1a3-4d5b-a497-ac7c892f414c.jpg)

This error comes up when i try to get the skin and champ, and i tried multiple times with the same result XD

**Comment by KebsCS** [comment]
Thank you for your report
The endpoint that was being called got removed and unfortunately I don't think it's coming back as it was just a leftover from older version of the client.
I'm sorry to say that, but I don't think there will be any more exploits released publicly from now on, as Riot instead of focusing on client's performance started to fix every exploit there is, even something as small as this.

**Comment by KebsCS** [comment]
Closing this, as the exploit no longer works and I removed it from the latest release
