### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dravenscript** [KebsCS/KBotExt#66]
This app is so good and I literally cant play league without it. I have a couple of suggestions

- Insta mute all in champ select
- button to dodge last second

Also one bug that happens this patch is that if you swap pick order the bot doesnt work. Thanks for reading

**Comment by itsalexq** [comment]
+1 for instamute

**Comment by KebsCS** [comment]
Hi, thank you for the suggestions
Instant mute and fix when swapping pick order added in https://github.com/KebsCS/KBotExt/commit/f07d72fc2f91db7012dfb81b960e4eacefc844be

Last second dodge is unfortunately impossible, because the client doesn't share the exact timer and the time can vary a lot depending on server and connection speed
